### ISSUE TITLE
Slider Thumb Icon disapear when it clicked.

### ISSUE THREAD

**Issue by dongsug-song** [nui-dali/NUITizenGallery#23]
copied from https://github.sec.samsung.net/NUI/TizenNUISamples/issues/157

Source: SliderTest1, SliderTest2
Issue: Slider Thumb icon disapear when it clicked.
Frequency : Always

this issue is under the review
https://github.com/Samsung/TizenFX/pull/3187

**Comment by everLEEst** [comment]
Solved.
