### ISSUE TITLE
CollectionView 관련 항목에서 target 이 느려지는 문제

### ISSUE THREAD

**Issue by dongsug-song** [nui-dali/NUITizenGallery#30]
안녕하세요.
NikeM 에 올려서 테스트를 해 보면, 특히 CollectionView 관련 테스트 에서 앱이 느려지는 현상이 있습니다. 
(자리에서 직접 보여 드렸던 내용 입니다.)
확인 부탁드립니다.
감사합니다.

**Comment by everLEEst** [comment]
This issue is resolved already.
